// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKZ8ix_pt7AbFhLCBSYMY4Dy0O0MYdza4',
    appId: '1:1059727462077:web:5183fbedc455ff3f4171d4',
    messagingSenderId: '1059727462077',
    projectId: 'ghrhack-b3e22',
    authDomain: 'ghrhack-b3e22.firebaseapp.com',
    databaseURL: 'https://ghrhack-b3e22-default-rtdb.firebaseio.com',
    storageBucket: 'ghrhack-b3e22.firebasestorage.app',
    measurementId: 'G-899KR3506V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSIbQnYWVcTQrj4OtUKUlnEAFeuIfYoQ0',
    appId: '1:1059727462077:android:f41bb6ad0d172da64171d4',
    messagingSenderId: '1059727462077',
    projectId: 'ghrhack-b3e22',
    databaseURL: 'https://ghrhack-b3e22-default-rtdb.firebaseio.com',
    storageBucket: 'ghrhack-b3e22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWlCJKFI520QH49rEmDqJ8zPsy18hvbkI',
    appId: '1:1059727462077:ios:b77df4f7b4209e684171d4',
    messagingSenderId: '1059727462077',
    projectId: 'ghrhack-b3e22',
    databaseURL: 'https://ghrhack-b3e22-default-rtdb.firebaseio.com',
    storageBucket: 'ghrhack-b3e22.firebasestorage.app',
    iosClientId: '1059727462077-bsnkcbbt8o3gdugsnuehv0shnipkvrti.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghrHack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWlCJKFI520QH49rEmDqJ8zPsy18hvbkI',
    appId: '1:1059727462077:ios:b77df4f7b4209e684171d4',
    messagingSenderId: '1059727462077',
    projectId: 'ghrhack-b3e22',
    databaseURL: 'https://ghrhack-b3e22-default-rtdb.firebaseio.com',
    storageBucket: 'ghrhack-b3e22.firebasestorage.app',
    iosClientId: '1059727462077-bsnkcbbt8o3gdugsnuehv0shnipkvrti.apps.googleusercontent.com',
    iosBundleId: 'com.example.ghrHack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKZ8ix_pt7AbFhLCBSYMY4Dy0O0MYdza4',
    appId: '1:1059727462077:web:d8a51afe957b39f34171d4',
    messagingSenderId: '1059727462077',
    projectId: 'ghrhack-b3e22',
    authDomain: 'ghrhack-b3e22.firebaseapp.com',
    databaseURL: 'https://ghrhack-b3e22-default-rtdb.firebaseio.com',
    storageBucket: 'ghrhack-b3e22.firebasestorage.app',
    measurementId: 'G-ZVP4YZ35ZJ',
  );
}
